### ISSUE TITLE
need help to download only single book

### ISSUE THREAD

**Issue by dev-lalit** [atlonxp/Calameo-SVG-Downloader#1]
thank you so much working just fine.but how can i download and save only single book and can you help me with converting these .svg files to a single pdf file. i tried svglibs with report labs. but some fonts are irregular or not showing . if there is a way to convert these SVG's into pdf. please help i tried but can't do it.

**Comment by atlonxp** [comment]
You can use Inkscape to convert all of svg into one pdf.

Note that "SVGZ" files on Calameo is not a real "SVGZ" but it is simple "SVG".

**Comment by dev-lalit** [comment]
> You can use Inkscape to convert all of svg into one pdf.
> 
> Note that "SVGZ" files on Calameo is not a real "SVGZ" but it is simple "SVG".

thank you i did it and it is working fine. thank you again but does your code can download only one chosen book. if it does than help me. also thank you very much for fast response of yours.

**Comment by atlonxp** [comment]
you may comment out the first for loop and add following code

```
books_list = ['{BOOK-URL-YOU-WANTED-TO-DOWNLOAD}', ]
for book in books_list:
    ...
```

So, it will download only the URLs you set.
