### ISSUE TITLE
Assistance Required

### ISSUE THREAD

**Issue by nyamprofi** [atlonxp/Calameo-SVG-Downloader#2]
Firstly thanks a lot for this great resource, though yet to get it to work for me.

I see this to be very useful for but unfortunately I am getting errors running the calameo-downloader.py

Not sure what I am doing wrong! so I have pasted the error in the attache text, for you to kindly check and assist.

Thanks a lot in advance for the great job you are doing.

I have followed and installed all the prerequisites, as well as added **'chromedriver'** executable to **PATH**, but still the issue persist

Kindly assist @atlonxp 

[new 35.txt](https://github.com/atlonxp/Calameo-SVG-Downloader/files/5250748/new.35.txt)

___

C:\Users\nyam\OneDrive\Coding\PycharmProjects\Calameo\venv\Scripts\python.exe C:/Users/nyam/OneDrive/Coding/PycharmProjects/Calameo-SVG-Downloader/calameo-downloader.py
Traceback (most recent call last):
  File "C:\Users\nyam\OneDrive\Coding\PycharmProjects\Calameo\venv\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\nyam\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\nyam\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/nyam/OneDrive/Coding/PycharmProjects/Calameo-SVG-Downloader/calameo-downloader.py", line 16, in <module>
    driver: WebDriver = webdriver.Chrome(f"{BASE_DIR}/data/drivers/chromedriver")
  File "C:\Users\nyam\OneDrive\Coding\PycharmProjects\Calameo\venv\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\nyam\OneDrive\Coding\PycharmProjects\Calameo\venv\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

Process finished with exit code 1

**Comment by atlonxp** [comment]
Isn't it obvious issue? It said Selenium cannot find "chromedriver". 

1. You need to download "chromedriver" that compatible to your operating system 
2. Put it into a folder "./data/drivers/")
3. You may need to update `driver = webdriver.Chrome(f"{BASE_DIR}/data/drivers/chromedriver")`

Remember that my source was written for Linux based operating system. if you use windows, you need to change PATH style.

Google "Selenium chromedriver windows", there are so so so many example available.

**Comment by nyamprofi** [comment]
Wow, @atlonxp, you are totally incredible!!! with how quick you come through with your responses. Thank you so much!.

I actually downloaded "chromedriver" by doing some research, and followed the steps at StackOverFlow [https://stackoverflow.com/questions/29858752/error-message-chromedriver-executable-needs-to-be-available-in-the-path](url) but I think as you pointed out, it's because I was doing it on a window based system.

I will have to do some research to know how to replicate the source script in windows, else I got to build a Linux Distro and start learning Linux to be able to follow your guide successfully. 

I will try to fire-up a virtual Ubuntu, or Kali to start the journey, though I have never used Linux OS before, It will be a great learning experience for me, I think. 

I totally appreciate your time Bross, and allow me to come to you if I require some more direction once I fire-up the Linux VM this afternoon if you don't mind.

Thank you,

**Comment by nyamprofi** [comment]
Hi @atlonxp 

Greetings, just to let you know, I fired-up my Linux VM and have been able to run the script successfully.

The only problem though is the rendering of the pages get out of order and affect the output. did you have same issue?

Thanks a lot. I am able to save the files and will 

### **PAGE from Script-downloaded:**
![image](https://user-images.githubusercontent.com/71571402/93725452-dd094c00-fb9e-11ea-902f-7ce06b908102.png)


### **PAGE from original site:**
![image](https://user-images.githubusercontent.com/71571402/93725494-4721f100-fb9f-11ea-81bd-72788f0752c9.png)

_**Let me know you response, and have a good day mate!**_
